export const DATE_FORMAT1 = "YYYY-MM-DD";
export const DATE_FORMAT2 = "DD MMM, YYYY";
export const DATE_FORMAT3 = "MMM YYYY";
export const DATE_FORMAT4 = "MMM-YYYY";
export const DATE_FORMAT5 = "DD, MMM yy";
export const DATE_FORMAT6 = "MMMM, DD YYYY";
export const DATE_FORMAT7 = "MMM DD, YYYY";
export const DATE_FORMAT8 = "YYYY";
export const TIME_FORMAT1 = "hh:mm a";